# Frontend Dockerfile - Multi-stage build with Alpine base images
# Stage 1: Build the application
FROM node:20-alpine 
# Set working directory
WORKDIR /app


# Copy source code
COPY msrit-frontend .

# Install dependencies
RUN npm install


# Expose port 80
EXPOSE 8080

CMD ["npm", "run", "dev"]
