apiVersion: v1
kind: Namespace
metadata:
  name: msrit-chatbot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: msrit-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: msrit-backend
          imagePullPolicy: Never
          env:
            - name: OLLAMA_HOST
              value: "ollama-service.msrit-chatbot.svc.cluster.local"
            - name: OLLAMA_PORT
              value: "11434"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: msrit-chatbot
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: msrit-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: msrit-frontend
          imagePullPolicy: Never
          env:
            - name: REACT_APP_API_URL
              value: "http://backend-service.msrit-chatbot.svc.cluster.local:5000"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: msrit-chatbot
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-storage-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/ollama"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-storage-pvc
  namespace: msrit-chatbot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: msrit-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      volumes:
        - name: ollama-storage
          persistentVolumeClaim:
            claimName: ollama-storage-pvc
      containers:
        - name: ollama
          image: ollama/ollama:latest
          ports:
            - containerPort: 11434
          volumeMounts:
            - name: ollama-storage
              mountPath: /root/.ollama
          command: ["/bin/sh", "-c"]
          args:
            - "ollama serve & sleep 2 && ollama pull gemma3:1b && tail -f /dev/null"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: msrit-chatbot
spec:
  type: ClusterIP
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
